### ISSUE TITLE
Question about AnyGrasp and AnyGrasp Open Source

### ISSUE THREAD

**Issue by JiXAllen** [ok-robot/ok-robot#14]
Thanks for your good open source work. 
Your paper shows the average performance comparison between AnyGrasp and AnyGrasp Open Source. And in Appendix A, they are called AnyGrasp and Open Graspness. What's the difference between the AnyGrasp and AnyGrasp Open Source?

**Comment by notmahi** [comment]
[GraspNet](https://graspnet.net/) is trained on some proprietary data, which is why the model isn't truly open source. We used an educational license to create this project and do our comparisons.

The open source AnyGrasp is a third party reimplementation found [here](https://github.com/graspnet/graspness_unofficial) that is linked to from the [AnyGrasp repo.](https://github.com/graspnet/anygrasp_sdk?tab=readme-ov-file#license-registration). It's understandably slightly worse than the closed-source AnyGrasp.
